sudo: required
language: node_js
notifications: 
  email: diegodulval@fai-mg.br
node_js:
- 6.11.1
services:
- postgresql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database moment_test;' -U postgres
- npm i -g sequelize-cli gulp-cli cross-env
- cd server/
- sequelize db:migrate --env test
- npm install
- gulp
script:
- npm run unit-test
- npm run integration-test